list: $/deanosborne/philter/models/image/columns.yaml
modelClass: deanosborne\Philter\Models\Image
title: Images
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'deanosborne/philter/images/update/:id'
